# Generated by Django 3.0.7 on 2020-06-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avRating',
            field=models.FloatField(default=0),
        ),
    ]
